FROM nginx:alpine

# Копируем HTML файл
COPY static/signin.html /usr/share/nginx/html/signin.html

# Копируем конфигурацию NGINX
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Открываем порт 80
EXPOSE 80

# Запускаем NGINX
CMD ["nginx", "-g", "daemon off;"] 